version: '3.3'
services:
  redis:
    image: redis:latest 
    container_name: redis_bbb
    ports:
      -  "6379:6379"
    volumes:
      - bbb-redis-data:/data
    restart: always

  bbb-server-service:
    container_name: bbb-serv-cont
    image: lnlscon/bbb-daemon-container:latest
    ports:
      -  "4850:4850"
      -  "6789:6789/tcp"
      -  "9877:9877/tcp"
      -  "9876:9876/udp"
    dns:
      - 10.0.0.71
      - 10.0.0.72
    env_file:
      -  /root/bbb-daemon/docker/bbb-server/bbb-server.env
    depends_on:
      -  redis
    restart: always

volumes:
  bbb-redis-data:
