version: '3.3'
services:
  redis:
    image: redis:latest 
    container_name: redis
    ports:
      -  "6379:6379"
    volumes:
      - bbb-redis-data:/data
    restart: always

volumes:
  bbb-redis-data:
    - /storage/epics-services/daemon/db/:/data
